import Foundation

/// How generated source is shaped.
public struct GeneratorOptions: Sendable {
    /// The namespace type holding the base URL and decoder factory. Defaults to the document title.
    public var namespace: String?
    /// Whether generated declarations are `public`.
    public var isPublic: Bool
    /// The spec's file name, recorded in the header so a reader knows what to regenerate from.
    public var sourceName: String

    /// Creates generation options.
    public init(namespace: String? = nil, isPublic: Bool = true, sourceName: String = "openapi.yaml") {
        self.namespace = namespace
        self.isPublic = isPublic
        self.sourceName = sourceName
    }
}

/// Renders an ``OpenAPIDocument`` as Swift source.
///
/// The output targets `EndpointDefinition` and ``EndpointRequestBuilder`` directly — never the
/// `@Endpoint` macro — so generated code compiles in packages that do not enable the macro trait
/// and carries no dependency beyond `NovaNetworkCore`.
public enum SwiftEndpointEmitter {
    /// Renders the document.
    public static func emit(_ document: OpenAPIDocument, options: GeneratorOptions) -> String {
        let access = options.isPublic ? "public " : ""
        let namespace = options.namespace ?? SwiftNaming.namespaceName(title: document.title)
        var sections: [String] = [header(document, options: options)]

        sections.append(namespaceSection(document, namespace: namespace, access: access))

        if !document.types.isEmpty {
            sections.append("// MARK: - Models")
            sections += document.types.map { type(for: $0, access: access) }
        }

        if !document.operations.isEmpty {
            sections.append("// MARK: - Operations")
            sections += document.operations.map {
                operation($0, namespace: namespace, hasServer: document.serverURL != nil, access: access)
            }
        }

        return sections.joined(separator: "\n\n") + "\n"
    }

    // MARK: - Header and namespace

    private static func header(_ document: OpenAPIDocument, options: GeneratorOptions) -> String {
        """
        // Generated by nova-openapi from \(options.sourceName). Do not edit: regenerating overwrites this file.
        // Source document: \(document.title) \(document.version)
        //
        // Regenerate with:
        //   swift package --allow-writing-to-package-directory nova-openapi \\
        //     --spec \(options.sourceName) --output <this file>

        import Foundation
        import NovaNetworkCore
        """
    }

    private static func namespaceSection(_ document: OpenAPIDocument, namespace: String, access: String) -> String {
        var members: [String] = []

        if let serverURL = document.serverURL {
            members.append(
                """
                /// The server declared by the source document.
                \(access)static let baseURL = URL(string: \(serverURL.swiftLiteral))!
                """
            )
        }

        let usesDates = document.types.contains { type in
            guard case let .object(_, properties, _) = type else {
                if case let .alias(_, target, _) = type { return target.mentionsDate }
                return false
            }
            return properties.contains { $0.type.mentionsDate }
        } || document.operations.contains { operation in
            operation.responseType?.mentionsDate == true
                || operation.parameters.contains { $0.type.mentionsDate }
                || operation.requestBody?.type.mentionsDate == true
        }

        members.append(
            """
            /// A decoder configured for this document's payloads.
            ///
            /// Pass it to `execute(endpoint:decoder:)`\(usesDates ? ": the document uses `date-time` values, which the default `JSONDecoder` does not read." : ".")
            \(access)static func makeDecoder() -> JSONDecoder {
                let decoder = JSONDecoder()\(usesDates ? "\n    decoder.dateDecodingStrategy = .iso8601" : "")
                return decoder
            }
            """
        )

        return """
        // MARK: - \(namespace)

        /// Namespace for values shared by every generated endpoint.
        \(access)enum \(namespace) {
        \(members.joined(separator: "\n\n").indentedBy(4))
        }
        """
    }

    // MARK: - Models

    private static func type(for type: GeneratedType, access: String) -> String {
        switch type {
        case let .object(name, properties, documentation):
            structure(name: name, properties: properties, documentation: documentation, access: access)
        case let .stringEnum(name, cases, documentation):
            stringEnum(name: name, cases: cases, documentation: documentation, access: access)
        case let .alias(name, target, documentation):
            "\(comment(documentation))\(access)typealias \(name) = \(target.rendered)"
        case let .anyJSON(name):
            anyJSON(name: name, access: access)
        case let .indirectBox(name):
            indirectBox(name: name, access: access)
        }
    }

    private static func structure(
        name: String,
        properties: [GeneratedProperty],
        documentation: String?,
        access: String
    ) -> String {
        var members = properties.map { property in
            "\(comment(property.documentation))\(access)var \(property.swiftName): \(property.type.rendered)"
        }

        let arguments = properties.map { property in
            let defaultValue = property.type.isOptional ? " = nil" : ""
            return "\(property.swiftName): \(property.type.rendered)\(defaultValue)"
        }
        let assignments = properties.map { "self.\($0.swiftName) = \($0.swiftName)" }

        members.append(
            """
            /// Creates a \(name) value.
            \(access)init(\(arguments.joined(separator: ", "))) {
            \(assignments.joined(separator: "\n").indentedBy(4))
            }
            """
        )

        if properties.contains(where: { $0.swiftName.unescaped != $0.wireName }) {
            let cases = properties.map { property in
                property.swiftName.unescaped == property.wireName
                    ? "case \(property.swiftName)"
                    : "case \(property.swiftName) = \(property.wireName.swiftLiteral)"
            }
            members.append(
                """
                private enum CodingKeys: String, CodingKey {
                \(cases.joined(separator: "\n").indentedBy(4))
                }
                """
            )
        }

        return """
        \(comment(documentation))\(access)struct \(name): Codable, Hashable, Sendable {
        \(members.joined(separator: "\n\n").indentedBy(4))
        }
        """
    }

    private static func stringEnum(
        name: String,
        cases: [GeneratedEnumCase],
        documentation: String?,
        access: String
    ) -> String {
        let members = cases.map { value in
            value.swiftName.unescaped == value.wireValue
                ? "case \(value.swiftName)"
                : "case \(value.swiftName) = \(value.wireValue.swiftLiteral)"
        }

        return """
        \(comment(documentation))\(access)enum \(name): String, Codable, Hashable, Sendable, CaseIterable, EndpointParameterConvertible {
        \(members.joined(separator: "\n").indentedBy(4))
        }
        """
    }

    private static func anyJSON(name: String, access: String) -> String {
        """
        /// A JSON value from a schema with no single Swift shape, such as a multi-branch `oneOf`.
        \(access)enum \(name): Codable, Hashable, Sendable {
            case null
            case bool(Bool)
            case number(Double)
            case string(String)
            case array([\(name)])
            case object([String: \(name)])

            \(access)init(from decoder: Decoder) throws {
                let container = try decoder.singleValueContainer()
                if container.decodeNil() {
                    self = .null
                } else if let value = try? container.decode(Bool.self) {
                    self = .bool(value)
                } else if let value = try? container.decode(Double.self) {
                    self = .number(value)
                } else if let value = try? container.decode(String.self) {
                    self = .string(value)
                } else if let value = try? container.decode([\(name)].self) {
                    self = .array(value)
                } else {
                    self = .object(try container.decode([String: \(name)].self))
                }
            }

            \(access)func encode(to encoder: Encoder) throws {
                var container = encoder.singleValueContainer()
                switch self {
                case .null: try container.encodeNil()
                case let .bool(value): try container.encode(value)
                case let .number(value): try container.encode(value)
                case let .string(value): try container.encode(value)
                case let .array(value): try container.encode(value)
                case let .object(value): try container.encode(value)
                }
            }
        }
        """
    }

    private static func indirectBox(name: String, access: String) -> String {
        """
        /// A value held behind a reference, used where a model would otherwise contain itself.
        ///
        /// Swift rejects a value type that stores itself, and an `Optional` does not help — it still
        /// stores its wrapped value inline. Read the value through ``wrapped``.
        \(access)struct \(name)<Wrapped: Sendable>: Sendable {
            private final class Storage: Sendable {
                let value: Wrapped

                init(_ value: Wrapped) {
                    self.value = value
                }
            }

            private let storage: Storage

            /// The boxed value.
            \(access)var wrapped: Wrapped {
                storage.value
            }

            /// Boxes a value.
            \(access)init(_ wrapped: Wrapped) {
                storage = Storage(wrapped)
            }
        }

        extension \(name): Equatable where Wrapped: Equatable {
            \(access)static func == (lhs: \(name)<Wrapped>, rhs: \(name)<Wrapped>) -> Bool {
                lhs.wrapped == rhs.wrapped
            }
        }

        extension \(name): Hashable where Wrapped: Hashable {
            \(access)func hash(into hasher: inout Hasher) {
                hasher.combine(wrapped)
            }
        }

        extension \(name): Decodable where Wrapped: Decodable {
            \(access)init(from decoder: Decoder) throws {
                self.init(try decoder.singleValueContainer().decode(Wrapped.self))
            }
        }

        extension \(name): Encodable where Wrapped: Encodable {
            \(access)func encode(to encoder: Encoder) throws {
                var container = encoder.singleValueContainer()
                try container.encode(wrapped)
            }
        }
        """
    }

    // MARK: - Operations

    private static func operation(
        _ operation: OpenAPIOperation,
        namespace: String,
        hasServer: Bool,
        access: String
    ) -> String {
        var members: [String] = [
            "\(access)typealias Response = \(operation.responseType?.rendered ?? "NoContent")",
        ]

        var initializerArguments: [String] = []
        var assignments: [String] = []

        if hasServer {
            members.append("\(access)var baseURL: URL { \(namespace).baseURL }")
        } else {
            members.append("/// The server this endpoint is sent to; the document declares none.\n\(access)var baseURL: URL")
            initializerArguments.append("baseURL: URL")
            assignments.append("self.baseURL = baseURL")
        }

        for parameter in operation.parameters {
            members.append("\(comment(parameter.documentation))\(access)var \(parameter.swiftName): \(parameter.type.rendered)")
            initializerArguments.append(
                "\(parameter.swiftName): \(parameter.type.rendered)\(parameter.type.isOptional ? " = nil" : "")"
            )
            assignments.append("self.\(parameter.swiftName) = \(parameter.swiftName)")
        }

        if let body = operation.requestBody {
            members.append("/// The request body.\n\(access)var \(body.swiftName): \(body.type.rendered)")
            initializerArguments.append("\(body.swiftName): \(body.type.rendered)\(body.type.isOptional ? " = nil" : "")")
            assignments.append("self.\(body.swiftName) = \(body.swiftName)")
        }

        members.append(
            """
            /// Creates the endpoint.
            \(access)init(\(initializerArguments.joined(separator: ", "))) {
            \(assignments.isEmpty ? "" : assignments.joined(separator: "\n").indentedBy(4))
            }
            """
        )
        members.append(makeRequest(operation, access: access))

        let availability = operation.isDeprecated ? "@available(*, deprecated)\n" : ""
        return """
        \(comment(operation.documentation))\(availability)\(access)struct \(operation.typeName): EndpointDefinition {
        \(members.joined(separator: "\n\n").indentedBy(4))
        }
        """
    }

    private static func makeRequest(_ operation: OpenAPIOperation, access: String) -> String {
        let hasWork = !operation.parameters.isEmpty || operation.requestBody != nil
        var lines = [
            "\(hasWork ? "var" : "let") builder = EndpointRequestBuilder(",
            "    method: .\(operation.method),",
            "    baseURL: baseURL,",
            "    path: \(operation.path.swiftLiteral)",
            ")",
        ]

        for parameter in operation.parameters where parameter.location == .path {
            lines.append("try builder.setPath(\(parameter.wireName.swiftLiteral), \(parameter.swiftName))")
        }
        for parameter in operation.parameters where parameter.location == .query {
            let style = parameter.queryStyle == ".repeated" ? "" : ", style: \(parameter.queryStyle)"
            lines.append("builder.addQuery(\(parameter.wireName.swiftLiteral), \(parameter.swiftName)\(style))")
        }
        for parameter in operation.parameters where parameter.location == .header {
            lines.append("builder.setHeader(\(parameter.wireName.swiftLiteral), \(parameter.swiftName))")
        }

        if let body = operation.requestBody {
            if body.contentType != "application/json" {
                lines.append("builder.setHeader(\"Content-Type\", \(body.contentType.swiftLiteral))")
            }
            if body.type.isOptional {
                lines.append("if let \(body.swiftName) {")
                lines.append("    try builder.setJSONBody(\(body.swiftName), encoder: jsonEncoder)")
                lines.append("}")
            } else {
                lines.append("try builder.setJSONBody(\(body.swiftName), encoder: jsonEncoder)")
            }
        }

        lines.append("return try builder.build(timeout: timeout, additionalHeaders: additionalHeaders)")

        return """
        /// Builds the request for this operation.
        \(access)func makeRequest() throws -> APIRequest {
        \(lines.joined(separator: "\n").indentedBy(4))
        }
        """
    }

    // MARK: - Formatting

    /// Renders documentation as `///` lines, or nothing when there is none.
    private static func comment(_ text: String?) -> String {
        guard let text, !text.isEmpty else { return "" }
        return text
            .split(separator: "\n", omittingEmptySubsequences: false)
            .map { $0.isEmpty ? "///" : "/// \($0)" }
            .joined(separator: "\n") + "\n"
    }
}

extension SwiftTypeReference {
    /// Whether the outermost layer is optional, which drives `= nil` initializer defaults.
    var isOptional: Bool {
        if case .optional = self { return true }
        return false
    }
}

extension String {
    /// The string as a Swift string literal.
    var swiftLiteral: String {
        var escaped = ""
        for character in self {
            switch character {
            case "\\": escaped += "\\\\"
            case "\"": escaped += "\\\""
            case "\n": escaped += "\\n"
            case "\t": escaped += "\\t"
            default: escaped.append(character)
            }
        }
        return "\"\(escaped)\""
    }

    /// The identifier without the backticks that escape Swift keywords.
    var unescaped: String {
        hasPrefix("`") && hasSuffix("`") && count > 1 ? String(dropFirst().dropLast()) : self
    }

    /// Every line indented by `width` spaces.
    func indentedBy(_ width: Int) -> String {
        let padding = String(repeating: " ", count: width)
        return split(separator: "\n", omittingEmptySubsequences: false)
            .map { $0.isEmpty ? "" : padding + $0 }
            .joined(separator: "\n")
    }
}
