import Foundation

/// Named overlays for the preset v2 composition model (`base preset + overlays`).
public enum NetworkClientPresetOverlayKind: String, Sendable, CaseIterable {
    case lowLatency = "low_latency"
    case strictReliability = "strict_reliability"
    case offlineDurability = "offline_durability"
    case highThroughput = "high_throughput"
}

/// Overlay payload that can be composed on top of a base ``NetworkClientPreset``.
public struct NetworkClientPresetOverlay: Sendable {
    /// Overlay identity.
    public let kind: NetworkClientPresetOverlayKind
    /// Optional retry policy replacement.
    public let retryPolicy: RetryPolicy?
    /// Optional default cache policy replacement.
    public let defaultCachePolicy: CachePolicy?
    /// Optional runtime policy override (merged field-by-field).
    public let runtimePolicy: NetworkClientRuntimePolicy?
    /// Merge-only request overrides.
    public let requestOverrides: NetworkClientPreset.RequestOverrides
    /// User-facing tradeoff notes introduced by this overlay.
    public let tradeoffs: [String]

    /// Creates an overlay for preset composition.
    public init(
        kind: NetworkClientPresetOverlayKind,
        retryPolicy: RetryPolicy? = nil,
        defaultCachePolicy: CachePolicy? = nil,
        runtimePolicy: NetworkClientRuntimePolicy? = nil,
        requestOverrides: NetworkClientPreset.RequestOverrides = .init(),
        tradeoffs: [String] = []
    ) {
        self.kind = kind
        self.retryPolicy = retryPolicy
        self.defaultCachePolicy = defaultCachePolicy
        self.runtimePolicy = runtimePolicy
        self.requestOverrides = requestOverrides
        self.tradeoffs = tradeoffs
    }
}

/// Severity level for preset validation issues.
public enum NetworkClientPresetValidationSeverity: String, Sendable {
    case warning
    case error
}

/// Single validation issue reported by ``NetworkClientPresetValidator``.
public struct NetworkClientPresetValidationIssue: Sendable {
    /// Stable issue code for CI/reporting.
    public let code: String
    /// Issue severity.
    public let severity: NetworkClientPresetValidationSeverity
    /// Human-readable issue description.
    public let message: String
    /// Suggested remediation path.
    public let recommendation: String

    /// Creates a validation issue.
    public init(
        code: String,
        severity: NetworkClientPresetValidationSeverity,
        message: String,
        recommendation: String
    ) {
        self.code = code
        self.severity = severity
        self.message = message
        self.recommendation = recommendation
    }
}

/// Aggregate validation result for production-readiness checks.
public struct NetworkClientPresetValidationReport: Sendable {
    /// All findings generated by the validator.
    public let issues: [NetworkClientPresetValidationIssue]

    /// Creates a validation report.
    public init(issues: [NetworkClientPresetValidationIssue]) {
        self.issues = issues
    }

    /// Returns `true` when the report has no blocking (`error`) issues.
    public var isProductionReady: Bool {
        !issues.contains { $0.severity == .error }
    }

    /// Returns only blocking (`error`) issues.
    public var blockingIssues: [NetworkClientPresetValidationIssue] {
        issues.filter { $0.severity == .error }
    }
}

/// Production onboarding goals used by ``NetworkClientProductionProfileGenerator``.
public enum NetworkClientProductionGoal: String, Sendable {
    case restAPI = "rest_api"
    case realtime = "realtime"
    case offlineFirst = "offline_first"
}

/// Generated onboarding artifact that includes composed config and validation output.
public struct NetworkClientProductionProfile: Sendable {
    /// Goal used to generate this profile.
    public let goal: NetworkClientProductionGoal
    /// Base preset chosen for this profile.
    public let basePreset: NetworkClientPreset
    /// Overlays applied to the base preset.
    public let overlays: [NetworkClientPresetOverlayKind]
    /// Final composed preset.
    public let composedPreset: NetworkClientPreset
    /// Validation report for anti-pattern checks.
    public let validation: NetworkClientPresetValidationReport

    /// Creates a generated production profile.
    public init(
        goal: NetworkClientProductionGoal,
        basePreset: NetworkClientPreset,
        overlays: [NetworkClientPresetOverlayKind],
        composedPreset: NetworkClientPreset,
        validation: NetworkClientPresetValidationReport
    ) {
        self.goal = goal
        self.basePreset = basePreset
        self.overlays = overlays
        self.composedPreset = composedPreset
        self.validation = validation
    }

    /// Generates a copy-paste bootstrap snippet for setup onboarding.
    public func bootstrapSnippet(
        presetVariableName: String = "preset",
        transportExpression: String = "Transport()",
        includeOfflineStore: Bool = false
    ) -> String {
        let basePresetName: String
        switch basePreset.kind {
        case .restHeavy:
            basePresetName = "restHeavy"
        case .realtimeHeavy:
            basePresetName = "realtimeHeavy"
        case .offlineFirst:
            basePresetName = "offlineFirst"
        }
        let overlaysLiteral = overlays.map { ".\($0)" }.joined(separator: ", ")
        let overlaysLine = overlays.isEmpty
            ? "let overlays: [NetworkClientPresetOverlayKind] = []"
            : "let overlays: [NetworkClientPresetOverlayKind] = [\(overlaysLiteral)]"
        let storeLine = includeOfflineStore ? ",\n    offlineWriteStore: DiskOfflineWriteStore(directoryURL: queueURL)" : ""
        return """
        \(overlaysLine)
        let \(presetVariableName) = NetworkClientPreset.compose(
            base: .\(basePresetName),
            overlays: overlays
        )

        let client = NetworkClient(
            transport: \(transportExpression),
            retryPolicy: \(presetVariableName).retryPolicy,
            defaultCachePolicy: \(presetVariableName).defaultCachePolicy\(storeLine)
        )
        await client.applyRuntimePolicy(from: \(presetVariableName))
        """
    }
}

/// Preset v2 composition engine (`base preset + overlays`).
public enum NetworkClientPresetComposer {
    /// Composes a base preset with overlays applied in sequence.
    public static func compose(
        base: NetworkClientPreset,
        overlays: [NetworkClientPresetOverlay]
    ) -> NetworkClientPreset {
        var retryPolicy = base.retryPolicy
        var defaultCachePolicy = base.defaultCachePolicy
        var runtimePolicy = base.runtimePolicy
        var requestOptions = base.defaultRequestOptions
        var tradeoffs = base.tradeoffs

        for overlay in overlays {
            if let value = overlay.retryPolicy {
                retryPolicy = value
            }
            if let value = overlay.defaultCachePolicy {
                defaultCachePolicy = value
            }
            if let value = overlay.runtimePolicy {
                runtimePolicy = merge(base: runtimePolicy, override: value)
            }
            requestOptions = requestOptions.applying(overlay.requestOverrides)
            tradeoffs.append(contentsOf: overlay.tradeoffs)
        }

        return NetworkClientPreset(
            kind: base.kind,
            retryPolicy: retryPolicy,
            defaultCachePolicy: defaultCachePolicy,
            runtimePolicy: runtimePolicy,
            defaultRequestOptions: requestOptions,
            tradeoffs: unique(tradeoffs)
        )
    }

    private static func merge(
        base: NetworkClientRuntimePolicy,
        override: NetworkClientRuntimePolicy
    ) -> NetworkClientRuntimePolicy {
        NetworkClientRuntimePolicy(
            retryPolicy: override.retryPolicy ?? base.retryPolicy,
            deadlineBudgetSeconds: override.deadlineBudgetSeconds ?? base.deadlineBudgetSeconds,
            circuitBreakerPolicy: override.circuitBreakerPolicy ?? base.circuitBreakerPolicy,
            coalescingPolicy: override.coalescingPolicy ?? base.coalescingPolicy
        )
    }

    private static func unique(_ values: [String]) -> [String] {
        var seen: Set<String> = []
        var result: [String] = []
        for value in values where seen.insert(value).inserted {
            result.append(value)
        }
        return result
    }
}

/// Validator for production profile anti-pattern checks.
public enum NetworkClientPresetValidator {
    /// Validates a composed preset for production-readiness and anti-patterns.
    public static func validate(
        preset: NetworkClientPreset,
        overlays: [NetworkClientPresetOverlayKind] = [],
        expectsOfflineDurability: Bool = false,
        offlineStoreConfigured: Bool = false
    ) -> NetworkClientPresetValidationReport {
        var issues: [NetworkClientPresetValidationIssue] = []
        let options = preset.defaultRequestOptions
        let queueEnabled = options.offlineQueuePolicy.mode != .disabled

        if preset.retryPolicy.maxAttempts < 2 {
            issues.append(.init(
                code: "AP-RETRY-001",
                severity: .warning,
                message: "Retry policy has no practical retry budget for transient failures.",
                recommendation: "Use maxAttempts >= 2 for production unless endpoint semantics prohibit retries."
            ))
        }

        if options.rateLimitPolicy == nil {
            issues.append(.init(
                code: "AP-RATE-001",
                severity: .warning,
                message: "No rate limit policy is configured in default request options.",
                recommendation: "Set RequestExecutionOptions.rateLimitPolicy to protect upstreams during client bursts."
            ))
        }

        if preset.runtimePolicy.circuitBreakerPolicy == nil && options.circuitBreakerPolicy == nil {
            issues.append(.init(
                code: "AP-CB-001",
                severity: .warning,
                message: "Circuit breaker is not configured at runtime or request level.",
                recommendation: "Enable circuit breaker policy to reduce cascading failures."
            ))
        }

        if options.deadlineBudgetSeconds == nil && preset.runtimePolicy.deadlineBudgetSeconds == nil {
            issues.append(.init(
                code: "AP-DEADLINE-001",
                severity: .warning,
                message: "No deadline budget configured for request execution.",
                recommendation: "Define a runtime or request deadline budget to avoid unbounded waits."
            ))
        }

        if queueEnabled && !offlineStoreConfigured {
            issues.append(.init(
                code: "AP-OFFLINE-001",
                severity: .error,
                message: "Offline queue is enabled but no durable offline write store is configured.",
                recommendation: "Configure DiskOfflineWriteStore (or custom OfflineWriteStore) before enabling offline queue."
            ))
        }

        if queueEnabled && options.idempotencyPolicy == nil {
            issues.append(.init(
                code: "AP-IDEMPOTENCY-001",
                severity: .warning,
                message: "Offline queue is enabled without idempotency policy.",
                recommendation: "Configure IdempotencyPolicy to reduce replay duplication risk."
            ))
        }

        if expectsOfflineDurability && !queueEnabled {
            issues.append(.init(
                code: "AP-OFFLINE-002",
                severity: .error,
                message: "Offline-first goal selected, but offline queue is disabled.",
                recommendation: "Enable offline queue mode (`enqueueWhenOffline` or `alwaysEnqueue`)."
            ))
        }

        if overlays.contains(.lowLatency) && overlays.contains(.offlineDurability) {
            issues.append(.init(
                code: "AP-OVERLAY-001",
                severity: .warning,
                message: "Selected overlays combine low-latency and offline-durability priorities.",
                recommendation: "Verify SLA tradeoffs and tune queue/rate limits for your dominant workload."
            ))
        }

        return .init(issues: issues)
    }
}

/// Onboarding generator that returns production-ready presets and validation output.
public struct NetworkClientProductionProfileGenerator: Sendable {
    /// Creates a generator instance.
    public init() {}

    /// Generates a production profile for the selected goal.
    public func generate(
        goal: NetworkClientProductionGoal,
        overlays explicitOverlays: [NetworkClientPresetOverlayKind] = [],
        offlineStoreConfigured: Bool = false
    ) -> NetworkClientProductionProfile {
        let basePreset: NetworkClientPreset
        let recommended: [NetworkClientPresetOverlayKind]

        switch goal {
        case .restAPI:
            basePreset = .restHeavy
            recommended = [.strictReliability]
        case .realtime:
            basePreset = .realtimeHeavy
            recommended = [.lowLatency, .highThroughput]
        case .offlineFirst:
            basePreset = .offlineFirst
            recommended = [.offlineDurability, .strictReliability]
        }

        let mergedKinds = Self.unique(explicitOverlays.isEmpty ? recommended : explicitOverlays)
        let composedPreset = NetworkClientPreset.compose(base: basePreset, overlays: mergedKinds)
        let validation = NetworkClientPresetValidator.validate(
            preset: composedPreset,
            overlays: mergedKinds,
            expectsOfflineDurability: goal == .offlineFirst,
            offlineStoreConfigured: offlineStoreConfigured
        )

        return .init(
            goal: goal,
            basePreset: basePreset,
            overlays: mergedKinds,
            composedPreset: composedPreset,
            validation: validation
        )
    }

    private static func unique(_ values: [NetworkClientPresetOverlayKind]) -> [NetworkClientPresetOverlayKind] {
        var seen: Set<NetworkClientPresetOverlayKind> = []
        var result: [NetworkClientPresetOverlayKind] = []
        for value in values where seen.insert(value).inserted {
            result.append(value)
        }
        return result
    }
}

public extension NetworkClientPreset {
    /// Returns a preset overlay descriptor by kind.
    static func overlay(_ kind: NetworkClientPresetOverlayKind) -> NetworkClientPresetOverlay {
        switch kind {
        case .lowLatency:
            return .init(
                kind: kind,
                retryPolicy: RetryPolicy(
                    maxAttempts: 2,
                    retryBudget: 2,
                    retryNonIdempotentRequests: false,
                    baseDelayNanoseconds: 80_000_000,
                    maxDelayNanoseconds: 500_000_000,
                    maxRetryAfterNanoseconds: 5_000_000_000,
                    respectRetryAfterHeader: true,
                    jitterRange: 0.95...1.1
                ),
                runtimePolicy: .init(
                    deadlineBudgetSeconds: 1.5,
                    coalescingPolicy: .init(dedupeTTLSeconds: 0.15)
                ),
                requestOverrides: .init(
                    priority: .high,
                    rateLimitPolicy: RateLimitPolicy(maxRequests: 40, intervalSeconds: 1)
                ),
                tradeoffs: [
                    "Overlay low-latency: tighter deadlines and lighter retries can increase fast-fail frequency."
                ]
            )
        case .strictReliability:
            let reliabilityCircuitBreaker = CircuitBreakerPolicy(
                scope: .host,
                failureThreshold: 4,
                cooldownSeconds: 6,
                halfOpenJitterSeconds: 0.8,
                probePolicy: .singleProbe
            )
            return .init(
                kind: kind,
                runtimePolicy: .init(circuitBreakerPolicy: reliabilityCircuitBreaker),
                requestOverrides: .init(
                    rateLimitPolicy: RateLimitPolicy(maxRequests: 10, intervalSeconds: 1),
                    idempotencyPolicy: .init(keyStrategy: .fingerprintDigest)
                ),
                tradeoffs: [
                    "Overlay strict-reliability: stronger protective limits may throttle burst traffic earlier."
                ]
            )
        case .offlineDurability:
            let queuePolicy = OfflineQueuePolicy(
                mode: .enqueueWhenOffline,
                maxEntries: 8_000,
                ttlSeconds: 14 * 24 * 60 * 60,
                maxReplayAttempts: 10,
                replayConflictPolicy: .manualReview,
                replayDedupeWindowSeconds: 48 * 60 * 60,
                replayPriority: .critical,
                replaySchedulerPolicy: .init()
            )
            return .init(
                kind: kind,
                defaultCachePolicy: .staleWhileRevalidate(maxAge: 20, staleAge: 180),
                requestOverrides: .init(
                    idempotencyPolicy: .init(keyStrategy: .fingerprintDigest),
                    offlineQueuePolicy: queuePolicy
                ),
                tradeoffs: [
                    "Overlay offline-durability: larger replay horizon improves delivery guarantees but increases local storage."
                ]
            )
        case .highThroughput:
            let throughputCircuitBreaker = CircuitBreakerPolicy(
                scope: .host,
                failureThreshold: 6,
                cooldownSeconds: 4,
                halfOpenJitterSeconds: 0.4,
                probePolicy: .parallelProbes(maxConcurrent: 3)
            )
            return .init(
                kind: kind,
                runtimePolicy: .init(circuitBreakerPolicy: throughputCircuitBreaker),
                requestOverrides: .init(
                    capacityScheduling: .queueByPriority,
                    rateLimitPolicy: RateLimitPolicy(maxRequests: 50, intervalSeconds: 1)
                ),
                tradeoffs: [
                    "Overlay high-throughput: increased parallel pressure may require tighter upstream monitoring."
                ]
            )
        }
    }

    /// Composes a base preset with overlays addressed by kind.
    static func compose(
        base: NetworkClientPreset,
        overlays kinds: [NetworkClientPresetOverlayKind]
    ) -> NetworkClientPreset {
        let overlays = kinds.map(Self.overlay(_:))
        return NetworkClientPresetComposer.compose(base: base, overlays: overlays)
    }

    /// Validates the preset for production-readiness and common anti-patterns.
    func validateProductionReadiness(
        overlays: [NetworkClientPresetOverlayKind] = [],
        expectsOfflineDurability: Bool = false,
        offlineStoreConfigured: Bool = false
    ) -> NetworkClientPresetValidationReport {
        NetworkClientPresetValidator.validate(
            preset: self,
            overlays: overlays,
            expectsOfflineDurability: expectsOfflineDurability,
            offlineStoreConfigured: offlineStoreConfigured
        )
    }
}

private extension RequestExecutionOptions {
    func applying(_ overrides: NetworkClientPreset.RequestOverrides) -> RequestExecutionOptions {
        RequestExecutionOptions(
            coalescerLimitsOverride: coalescerLimitsOverride,
            priority: overrides.priority ?? priority,
            capacityScheduling: overrides.capacityScheduling ?? capacityScheduling,
            coalescingMode: overrides.coalescingMode ?? coalescingMode,
            deadlineBudgetSeconds: overrides.deadlineBudgetSeconds ?? deadlineBudgetSeconds,
            circuitBreakerPolicy: overrides.circuitBreakerPolicy ?? circuitBreakerPolicy,
            rateLimitPolicy: overrides.rateLimitPolicy ?? rateLimitPolicy,
            idempotencyPolicy: overrides.idempotencyPolicy ?? idempotencyPolicy,
            offlineQueuePolicy: overrides.offlineQueuePolicy ?? offlineQueuePolicy
        )
    }
}
