import Foundation
import Testing
import NovaNetworkClient
import NovaNetworkOpenAPI
import NovaNetworkPetstoreGenerated

// Requirements: FR-18 (deterministic, collision-free names), FR-19 (models), FR-20 (parameters),
// FR-21 (responses), FR-22 (identifier mapping), FR-23 (generated code needs only the runtime),
// FR-24 (warnings, never silent), FR-26 (decoder factory), AR-1 (unchanged runtime behavior),
// EC-6, EC-7, EC-9, EC-10.
// Tests: T-18.1, T-18.2, T-19.1, T-19.2, T-20.1, T-21.1, T-21.2, T-22.1, T-23.1, T-24.1, T-24.2,
// T-26.1, T-27.1.

/// The repository root, found relative to this file so fixtures need no bundle resources.
private let repositoryRoot = URL(fileURLWithPath: #filePath)
    .deletingLastPathComponent()
    .deletingLastPathComponent()
    .deletingLastPathComponent()

private let petstoreSpecURL = repositoryRoot.appending(path: "Examples/OpenAPIPetstore/petstore.yaml")
private let generatedFileURL = repositoryRoot.appending(path: "Examples/OpenAPIPetstore/Generated/GeneratedPetstoreAPI.swift")

private func generatePetstore() throws -> GenerationResult {
    try OpenAPIGenerator.generate(
        specText: String(contentsOf: petstoreSpecURL, encoding: .utf8),
        options: GeneratorOptions(sourceName: "petstore.yaml")
    )
}

// MARK: - T-18.1, T-18.2, T-23.1 determinism and drift

@Suite
struct OpenAPIGenerationOutputTests {
    @Test
    func generatingTheSameDocumentTwiceProducesIdenticalBytes() throws {
        #expect(try generatePetstore().source == generatePetstore().source)
    }

    @Test
    func theCheckedInGeneratedFileMatchesWhatTheGeneratorProducesNow() throws {
        let onDisk = try String(contentsOf: generatedFileURL, encoding: .utf8)

        #expect(
            try generatePetstore().source == onDisk,
            """
            Examples/OpenAPIPetstore/Generated/GeneratedPetstoreAPI.swift is stale. Regenerate it:
            swift run nova-openapi --spec Examples/OpenAPIPetstore/petstore.yaml \
            --output Examples/OpenAPIPetstore/Generated/GeneratedPetstoreAPI.swift
            """
        )
    }

    @Test
    func generatedCodeImportsOnlyTheRuntimeAndNeverTheMacro() throws {
        let source = try generatePetstore().source

        #expect(source.contains("import NovaNetworkCore"))
        #expect(!source.contains("NovaNetworkMacros"))
        #expect(!source.contains("@Endpoint"))
    }

    @Test
    func operationNamesComeFromOperationIdOrTheMethodAndPath() throws {
        let source = try generatePetstore().source

        #expect(source.contains("public struct ListPets: EndpointDefinition"))
        #expect(source.contains("public struct GetPetById: EndpointDefinition"))
        // No operationId on DELETE /pets/{petId}, so the name is derived from method and path.
        #expect(source.contains("public struct DeletePetsByPetId: EndpointDefinition"))
    }

    @Test
    func theHeaderNamesTheSourceDocumentAndHowToRegenerate() throws {
        let source = try generatePetstore().source

        #expect(source.hasPrefix("// Generated by nova-openapi from petstore.yaml."))
        #expect(source.contains("swift package --allow-writing-to-package-directory nova-openapi"))
        #expect(source.contains("Source document: Petstore 1.4.0"))
    }

    @Test
    func generationOfTheReferenceDocumentStaysUnderTwoSeconds() throws {
        let specText = try String(contentsOf: petstoreSpecURL, encoding: .utf8)
        let start = Date()
        _ = try OpenAPIGenerator.generate(specText: specText)

        #expect(Date().timeIntervalSince(start) < 2)
    }
}

// MARK: - T-19.1, T-21.x, T-22.1, T-26.1 generated types

@Suite
struct GeneratedPetstoreTypeTests {
    @Test
    func modelsDecodeAPayloadFromTheDocumentIncludingRenamedAndKeywordFields() throws {
        let payload = Data(
            """
            {
              "id": 7,
              "name": "Ada",
              "tag": "tabby",
              "default": "none",
              "created_at": "2026-08-24T09:41:00Z",
              "status": "available",
              "dimensions": {"width": 10.5, "height": 4}
            }
            """.utf8
        )

        let pet = try PetstoreAPI.makeDecoder().decode(Pet.self, from: payload)

        #expect(pet.id == 7)
        #expect(pet.name == "Ada")
        #expect(pet.default == "none")
        #expect(pet.createdAt == ISO8601DateFormatter().date(from: "2026-08-24T09:41:00Z"))
        #expect(pet.status == .available)
        #expect(pet.dimensions?.width == 10.5)
        #expect(pet.parent == nil)
    }

    @Test
    func aRecursiveSchemaIsUsableThroughItsBox() throws {
        let ancestor = Pet(name: "Grace", id: 1)
        let pet = Pet(name: "Ada", id: 2, parent: Indirect(ancestor))

        let round = try PetstoreAPI.makeDecoder().decode(
            Pet.self,
            from: try JSONEncoder().encode(pet)
        )

        #expect(round.parent?.wrapped.name == "Grace")
        #expect(round == pet)
    }

    @Test
    func theDecoderFactoryReadsTheDateFormatTheDocumentDeclares() throws {
        let iso = Data(#"{"id":1,"name":"Ada","created_at":"2026-08-24T09:41:00Z"}"#.utf8)

        #expect(throws: Never.self) { try PetstoreAPI.makeDecoder().decode(Pet.self, from: iso) }
        #expect(throws: (any Error).self) { try JSONDecoder().decode(Pet.self, from: iso) }
    }

    @Test
    func enumSchemasBecomeRawValueEnumsUsableAsParameters() {
        #expect(PetStatus.allCases.map(\.rawValue) == ["available", "pending", "sold"])
        #expect(PetStatus.sold.endpointParameterStrings == ["sold"])
    }

    @Test
    func operationsCarryTheResponseTypeFromTheirLowest2xxResponse() {
        #expect(ListPets.Response.self == [Pet].self)
        #expect(GetPetById.Response.self == Pet.self)
        #expect(GetPetPhotoMetadata.Response.self == PhotoMetadata.self)
    }

    @Test
    func anOperationWithNoResponseContentDecodesAnEmptyBody() throws {
        #expect(DeletePetsByPetId.Response.self == NoContent.self)
        #expect(try DeletePetsByPetId(petId: 1).decode(Data(), using: JSONDecoder()) == NoContent())
    }
}

// MARK: - T-20.1 parameters

@Suite
struct GeneratedPetstoreRequestTests {
    @Test
    func pathQueryAndHeaderParametersLandWhereTheSpecPutsThem() throws {
        let request = try ListPets(
            limit: 20,
            tags: ["kitten", "rescue"],
            xRequestId: UUID(uuidString: "3F2504E0-4F89-11D3-9A0C-0305E82C3301")
        ).makeRequest()

        #expect(request.method == .get)
        #expect(request.url.absoluteString == "https://api.petstore.example.com/v1/pets")
        // explode: false in the document, so the array is comma-joined rather than repeated.
        #expect(request.queryItems == [
            URLQueryItem(name: "limit", value: "20"),
            URLQueryItem(name: "tags", value: "kitten,rescue"),
        ])
        #expect(request.headers["X-Request-Id"] == "3F2504E0-4F89-11D3-9A0C-0305E82C3301")
    }

    @Test
    func optionalParametersAreOmittedRatherThanSentEmpty() throws {
        let request = try ListPets().makeRequest()

        #expect(request.queryItems.isEmpty)
        #expect(request.headers.isEmpty)
    }

    @Test
    func aPathLevelParameterAppliesToEveryOperationUnderThatPath() throws {
        #expect(try GetPetById(petId: 42).makeRequest().url.path() == "/v1/pets/42")
        #expect(try DeletePetsByPetId(petId: 42).makeRequest().url.path() == "/v1/pets/42")
    }

    @Test
    func aRequiredRequestBodyIsEncodedAsJSON() throws {
        let request = try CreatePet(body: NewPet(name: "Ada", tag: "tabby")).makeRequest()

        #expect(request.method == .post)
        #expect(request.headers["Content-Type"] == "application/json")
        #expect(try JSONDecoder().decode(NewPet.self, from: #require(request.body)).name == "Ada")
    }

    @Test
    func anOptionalRequestBodyIsSkippedWhenAbsent() throws {
        let withoutBody = try UpdatePet(petId: 1).makeRequest()
        let withBody = try UpdatePet(petId: 1, body: NewPet(name: "Ada")).makeRequest()

        #expect(withoutBody.body == nil)
        #expect(withoutBody.headers["Content-Type"] == nil)
        #expect(withBody.body != nil)
    }
}

// MARK: - T-24.1, T-24.2, T-19.2, EC-6 warnings

@Suite
struct OpenAPIGenerationWarningTests {
    @Test
    func aMultiBranchOneOfWarnsAndFallsBackRatherThanFailing() throws {
        let result = try generatePetstore()
        let warning = result.warnings.first { $0.location.contains("payload/oneOf") }

        #expect(warning?.message.contains("GeneratedAnyJSON") == true)
        #expect(result.source.contains("public var payload: GeneratedAnyJSON?"))
    }

    @Test
    func aReferenceCycleIsReportedAndBoxedRatherThanLeftUncompilable() throws {
        let result = try generatePetstore()
        let warning = result.warnings.first { $0.location.hasSuffix("Pet/properties/parent") }

        #expect(warning?.message.contains("reference cycle") == true)
        #expect(result.source.contains("public var parent: Indirect<Pet>?"))
    }

    @Test
    func anAllOfCycleBetweenTwoSchemasIsReportedInsteadOfLoopingForever() throws {
        let spec = """
        openapi: 3.1.0
        info: {title: Cycles, version: 1.0.0}
        paths: {}
        components:
          schemas:
            A:
              allOf:
                - $ref: "#/components/schemas/B"
            B:
              allOf:
                - $ref: "#/components/schemas/A"
        """

        let result = try OpenAPIGenerator.generate(specText: spec)

        #expect(result.warnings.contains { $0.message.contains("Reference cycle") })
    }

    @Test
    func aDocumentWithoutServersTakesTheBaseURLAsAnInitializerParameter() throws {
        let spec = """
        openapi: 3.0.3
        info: {title: Serverless, version: 1.0.0}
        paths:
          /ping:
            get:
              operationId: ping
              responses:
                "204": {description: Pong.}
        """

        let result = try OpenAPIGenerator.generate(specText: spec)

        #expect(result.warnings.contains { $0.location == "#/servers" })
        #expect(result.source.contains("public var baseURL: URL"))
        #expect(result.source.contains("public init(baseURL: URL)"))
    }

    @Test
    func aNonJSONPayloadIsReportedRatherThanGeneratedWrong() throws {
        let spec = """
        openapi: 3.1.0
        info: {title: Files, version: 1.0.0}
        paths:
          /file:
            get:
              operationId: getFile
              responses:
                "200":
                  description: Bytes.
                  content:
                    application/octet-stream:
                      schema: {type: string, format: binary}
        """

        let result = try OpenAPIGenerator.generate(specText: spec)

        #expect(result.warnings.contains { $0.message.contains("No JSON media type") })
        #expect(result.source.contains("typealias Response = NoContent"))
    }

    @Test
    func securitySchemeSecretsNeverReachGeneratedSource() throws {
        let source = try generatePetstore().source

        #expect(!source.contains("hunter2"))
        #expect(!source.contains("X-API-Key"))
        #expect(!source.lowercased().contains("securityscheme"))
    }

    @Test
    func aDocumentThatIsNotOpenAPI3IsRejectedWithAnActionableMessage() {
        #expect(throws: GenerationError.self) {
            try OpenAPIGenerator.generate(specText: "swagger: \"2.0\"\ninfo: {title: Old, version: 1}\n")
        }
    }

    @Test
    func warningsFormatForABuildLog() {
        let warning = GenerationWarning(location: "#/paths/~1pets/get", message: "Something to know.")

        #expect(warning.formatted == "warning: #/paths/~1pets/get: Something to know.")
    }
}

// MARK: - T-27.1 unchanged runtime behavior

/// Records the requests the client hands to the transport.
private actor RecordingTransport: NetworkTransport {
    private(set) var requests: [APIRequest] = []
    private let body: Data

    init(body: Data) {
        self.body = body
    }

    func execute(_ request: APIRequest) async throws -> NetworkResponse {
        requests.append(request)
        return NetworkResponse(statusCode: 200, headers: ["Content-Type": "application/json"], body: body)
    }

    func recorded() -> [APIRequest] { requests }
}

@Suite
struct GeneratedEndpointExecutionTests {
    @Test
    func aGeneratedEndpointExecutesExactlyLikeItsHandWrittenEquivalent() async throws {
        let payload = Data(#"{"id":7,"name":"Ada"}"#.utf8)
        let generatedTransport = RecordingTransport(body: payload)
        let handWrittenTransport = RecordingTransport(body: payload)

        let generatedClient = NetworkClient(transport: generatedTransport)
        let handWrittenClient = NetworkClient(transport: handWrittenTransport)

        let generated = try await generatedClient.execute(
            endpoint: GetPetById(petId: 7),
            authScope: "petstore",
            decoder: PetstoreAPI.makeDecoder()
        )

        let handWritten = try await handWrittenClient.execute(
            endpoint: AnyEndpoint(
                request: APIRequest(
                    method: .get,
                    url: URL(string: "https://api.petstore.example.com/v1/pets/7")!
                ),
                response: Pet.self
            ),
            authScope: "petstore",
            decoder: PetstoreAPI.makeDecoder()
        )

        let generatedRequests = await generatedTransport.recorded()
        let handWrittenRequests = await handWrittenTransport.recorded()

        #expect(generated == handWritten)
        #expect(generatedRequests.count == 1)
        #expect(generatedRequests[0].url == handWrittenRequests[0].url)
        #expect(generatedRequests[0].method == handWrittenRequests[0].method)
        #expect(generatedRequests[0].headers == handWrittenRequests[0].headers)
        #expect(generatedRequests[0].queryItems == handWrittenRequests[0].queryItems)
    }
}
